"""Mission Rule Packs - Explainable task generation rules.

Each pack is a self-contained set of rules that:
1. Evaluate context conditions
2. Generate missions with clear reasoning
3. Track which pack/rule created each task

Rule Packs:
- WeatherPack: Indoor/outdoor, carry umbrella, reschedule
- CalendarPack: Prep, travel buffer, post-meeting notes
- GitHubPack: Issue spike → bugfix block, PR review → review block
- NewsPack: AI regulation → briefing task, tech layoffs → impact analysis
"""

from __future__ import annotations

import random
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Optional, Literal


Category = Literal["work", "study", "health", "admin", "dev"]
EnergyCost = Literal["low", "medium", "high"]


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _iso_in_hours(hours: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(hours=hours)).isoformat().replace("+00:00", "Z")


def _iso_in_minutes(minutes: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(minutes=minutes)).isoformat().replace("+00:00", "Z")


@dataclass
class GeneratedMission:
    """A mission generated by a rule pack."""
    title: str
    priority: str
    category: Category
    energy_cost: EnergyCost
    duration_minutes: int
    deadline_hours: Optional[int]
    tags: list[str]
    why: str
    pack_name: str
    rule_name: str
    sources: list[str]
    confidence: float = 0.7
    suggested_time: Optional[str] = None  # e.g., "14:00-14:30"
    conflicts: list[str] = field(default_factory=list)
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "priority": self.priority,
            "category": self.category,
            "energy_cost": self.energy_cost,
            "duration_minutes": self.duration_minutes,
            "deadline": _iso_in_hours(self.deadline_hours) if self.deadline_hours else None,
            "tags": self.tags,
            "why": self.why,
            "rule_pack": {
                "pack": self.pack_name,
                "rule": self.rule_name,
            },
            "sources": self.sources,
            "confidence": self.confidence,
            "scheduling": {
                "suggested_time": self.suggested_time,
                "conflicts": self.conflicts,
            },
        }


class RulePack(ABC):
    """Base class for rule packs."""
    
    name: str = "base"
    description: str = "Base rule pack"
    
    @abstractmethod
    def evaluate(self, context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
        """Evaluate context and return generated missions."""
        pass


class WeatherPack(RulePack):
    """Weather-driven task rules.
    
    Rules:
    - indoor_shift: Rain/storm → shift to indoor activities
    - outdoor_reminder: Clear weather → suggest outdoor break
    - carry_umbrella: Rain forecast → umbrella reminder
    - cold_alert: Low temp → dress warmly, limit outdoor
    - heat_alert: High temp → hydration, avoid midday outdoor
    """
    
    name = "weather"
    description = "Weather-driven planning and health rules"
    
    def evaluate(self, context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
        preferences = preferences or {}
        missions = []
        weather = context.get("weather") or {}
        
        condition = (weather.get("condition") or "").lower()
        temp_c = weather.get("temp_c")
        city = weather.get("city", "Unknown")
        
        # Rule: indoor_shift
        if any(c in condition for c in ["rain", "storm", "thunder", "snow"]):
            severity = "yüksek" if "storm" in condition or "thunder" in condition else "orta"
            missions.append(GeneratedMission(
                title="Dış mekan planlarını iç mekana taşı",
                priority="P2" if severity == "yüksek" else "P3",
                category="admin",
                energy_cost="low",
                duration_minutes=15,
                deadline_hours=2,
                tags=["weather", "planning", "indoor"],
                why=f"🌧️ {city}'de hava {condition}. Dış aktiviteleri ertele veya iç mekana al.",
                pack_name=self.name,
                rule_name="indoor_shift",
                sources=["weather"],
                confidence=0.85 if severity == "yüksek" else 0.7,
            ))
        
        # Rule: outdoor_break
        elif any(c in condition for c in ["clear", "sunny", "partly"]):
            if temp_c and 15 <= temp_c <= 28:
                missions.append(GeneratedMission(
                    title="Dışarıda 15dk yürüyüş molası",
                    priority="P4",
                    category="health",
                    energy_cost="low",
                    duration_minutes=15,
                    deadline_hours=4,
                    tags=["weather", "health", "outdoor", "break"],
                    why=f"☀️ Hava güzel ({temp_c}°C, {condition}). Kısa bir yürüyüş verimliliği artırır.",
                    pack_name=self.name,
                    rule_name="outdoor_break",
                    sources=["weather"],
                    confidence=0.6,
                    suggested_time="14:00-14:15",
                ))
        
        # Rule: carry_umbrella
        if any(c in condition for c in ["rain", "drizzle", "shower"]):
            missions.append(GeneratedMission(
                title="Şemsiye almayı unutma",
                priority="P3",
                category="admin",
                energy_cost="low",
                duration_minutes=1,
                deadline_hours=1,
                tags=["weather", "reminder"],
                why=f"🌂 {condition.title()} bekleniyor. Dışarı çıkarken şemsiye al.",
                pack_name=self.name,
                rule_name="carry_umbrella",
                sources=["weather"],
                confidence=0.9,
            ))
        
        # Rule: cold_alert
        if temp_c is not None and temp_c < 5:
            missions.append(GeneratedMission(
                title="Soğuk hava: kalın giyin, dış aktiviteleri sınırla",
                priority="P3",
                category="health",
                energy_cost="low",
                duration_minutes=5,
                deadline_hours=2,
                tags=["weather", "health", "cold"],
                why=f"🥶 Sıcaklık {temp_c}°C. Kalın giyinmeyi unutma ve dışarıda uzun kalma.",
                pack_name=self.name,
                rule_name="cold_alert",
                sources=["weather"],
                confidence=0.8,
            ))
        
        # Rule: heat_alert
        if temp_c is not None and temp_c > 32:
            missions.append(GeneratedMission(
                title="Sıcak hava: bol su iç, öğlen dışarı çıkma",
                priority="P2",
                category="health",
                energy_cost="low",
                duration_minutes=5,
                deadline_hours=1,
                tags=["weather", "health", "heat", "hydration"],
                why=f"🥵 Sıcaklık {temp_c}°C. Öğle saatlerinde dışarı çıkmaktan kaçın, bol su iç.",
                pack_name=self.name,
                rule_name="heat_alert",
                sources=["weather"],
                confidence=0.85,
            ))
        
        return missions


class CalendarPack(RulePack):
    """Calendar-driven task rules.
    
    Rules:
    - meeting_prep: Meeting coming → prepare agenda/notes
    - travel_buffer: Back-to-back meetings → add travel time
    - post_meeting: After meeting → write summary notes
    - overload_warning: Too many events → focus protection
    """
    
    name = "calendar"
    description = "Calendar-driven preparation and focus rules"
    
    def evaluate(self, context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
        preferences = preferences or {}
        missions = []
        calendar = context.get("calendar") or {}
        
        events_today = calendar.get("events_today", 0)
        events = calendar.get("events", [])
        
        # Rule: meeting_prep
        if events:
            next_event = events[0] if isinstance(events, list) and len(events) > 0 else None
            if next_event and isinstance(next_event, dict):
                event_title = next_event.get("title", "Toplantı")
                missions.append(GeneratedMission(
                    title=f"'{event_title}' için hazırlık yap",
                    priority="P2",
                    category="work",
                    energy_cost="medium",
                    duration_minutes=15,
                    deadline_hours=1,
                    tags=["calendar", "meeting", "prep"],
                    why=f"📅 Yaklaşan etkinlik: {event_title}. Gündem ve notları hazırla.",
                    pack_name=self.name,
                    rule_name="meeting_prep",
                    sources=["calendar"],
                    confidence=0.75,
                    suggested_time=next_event.get("suggested_prep_time"),
                ))
        
        # Rule: overload_warning
        if events_today > 5:
            missions.append(GeneratedMission(
                title="Yoğun gün: 30dk koruma bloğu ayır",
                priority="P2",
                category="work",
                energy_cost="low",
                duration_minutes=30,
                deadline_hours=3,
                tags=["calendar", "focus", "protection"],
                why=f"📆 Bugün {events_today} etkinlik var. Odaklanma için koruma bloğu şart.",
                pack_name=self.name,
                rule_name="overload_warning",
                sources=["calendar"],
                confidence=0.8,
                suggested_time="10:00-10:30 veya 15:00-15:30",
            ))
        elif events_today > 3:
            missions.append(GeneratedMission(
                title="Orta yoğunluklu gün: molaları planla",
                priority="P3",
                category="health",
                energy_cost="low",
                duration_minutes=10,
                deadline_hours=4,
                tags=["calendar", "wellness", "breaks"],
                why=f"📆 {events_today} etkinlik var. Araya kısa molalar ekle.",
                pack_name=self.name,
                rule_name="moderate_day",
                sources=["calendar"],
                confidence=0.65,
            ))
        
        # Rule: post_meeting (synthetic, for demo)
        if events_today > 0:
            missions.append(GeneratedMission(
                title="Toplantı sonrası: 5dk özet notu yaz",
                priority="P3",
                category="work",
                energy_cost="low",
                duration_minutes=5,
                deadline_hours=6,
                tags=["calendar", "meeting", "notes", "follow-up"],
                why="📝 Her toplantı sonrası kısa özet yazmak, aksiyon maddelerini kaçırmamak için önemli.",
                pack_name=self.name,
                rule_name="post_meeting_notes",
                sources=["calendar"],
                confidence=0.7,
            ))
        
        return missions


class GitHubPack(RulePack):
    """GitHub-driven development task rules.
    
    Rules:
    - pr_review_block: Open PRs → schedule review time
    - issue_spike: Sudden increase → triage session
    - bugfix_block: Critical issues → focused fix time
    - code_review_needed: Stale PRs → ping reviewers
    """
    
    name = "github"
    description = "GitHub workload management rules"
    
    def evaluate(self, context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
        preferences = preferences or {}
        missions = []
        github = context.get("github") or {}
        
        open_prs = github.get("open_prs", 0)
        open_issues = github.get("open_issues", 0)
        repo = github.get("repo", "repo")
        
        # Rule: pr_review_block
        if open_prs >= 5:
            missions.append(GeneratedMission(
                title="PR Review bloğu: 45dk ayır",
                priority="P1",
                category="dev",
                energy_cost="high",
                duration_minutes=45,
                deadline_hours=3,
                tags=["github", "code-review", "pr", "critical"],
                why=f"🔥 {open_prs} açık PR var. Review gecikmesi merge conflict ve deployment riskini artırıyor.",
                pack_name=self.name,
                rule_name="pr_review_block",
                sources=["github"],
                confidence=0.9,
                suggested_time="09:00-09:45 veya 14:00-14:45",
            ))
        elif open_prs >= 3:
            missions.append(GeneratedMission(
                title="PR'ları gözden geçir ve önceliklendir",
                priority="P2",
                category="dev",
                energy_cost="medium",
                duration_minutes=20,
                deadline_hours=6,
                tags=["github", "code-review", "pr"],
                why=f"📋 {open_prs} açık PR var. Hangilerinin acil olduğunu belirle.",
                pack_name=self.name,
                rule_name="pr_prioritize",
                sources=["github"],
                confidence=0.75,
            ))
        
        # Rule: issue_spike (when issues > 10)
        if open_issues >= 15:
            missions.append(GeneratedMission(
                title="Issue Triage oturumu: 30dk",
                priority="P1",
                category="dev",
                energy_cost="medium",
                duration_minutes=30,
                deadline_hours=4,
                tags=["github", "triage", "issues", "critical"],
                why=f"🚨 Issue sayısı {open_issues}'e ulaştı! Acil etiketleme ve atama gerekli.",
                pack_name=self.name,
                rule_name="issue_spike_triage",
                sources=["github"],
                confidence=0.85,
            ))
        elif open_issues >= 10:
            missions.append(GeneratedMission(
                title="Issue backlog temizliği yap",
                priority="P2",
                category="dev",
                energy_cost="medium",
                duration_minutes=20,
                deadline_hours=8,
                tags=["github", "triage", "issues", "maintenance"],
                why=f"📦 {open_issues} açık issue var. Eski/duplicate olanları kapat, öncelikleri güncelle.",
                pack_name=self.name,
                rule_name="issue_triage",
                sources=["github"],
                confidence=0.7,
            ))
        
        # Rule: bugfix_block (if issues imply bugs)
        if open_issues >= 5:
            missions.append(GeneratedMission(
                title="Bugfix bloğu: 1 saat odaklı düzeltme",
                priority="P2",
                category="dev",
                energy_cost="high",
                duration_minutes=60,
                deadline_hours=12,
                tags=["github", "bugfix", "focused-work"],
                why=f"🐛 {open_issues} açık issue var. 1 saatlik odaklı çalışma ile 2-3 bug kapatılabilir.",
                pack_name=self.name,
                rule_name="bugfix_block",
                sources=["github"],
                confidence=0.7,
                suggested_time="10:00-11:00",
            ))
        
        return missions


class NewsPack(RulePack):
    """News-driven awareness task rules.
    
    Rules:
    - ai_regulation_brief: AI regulation news → summarize
    - tech_layoffs_impact: Layoff news → impact analysis
    - security_alert: Security breach → review own systems
    - general_brief: Top news → 5min summary
    """
    
    name = "news"
    description = "News-driven awareness and briefing rules"
    
    def evaluate(self, context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
        preferences = preferences or {}
        missions = []
        news = context.get("news") or []
        
        if not news:
            return missions
        
        # Combine all titles for keyword search
        all_titles = " ".join([
            (n.get("title", "") if isinstance(n, dict) else str(n)).lower()
            for n in news
        ])
        
        # Rule: ai_regulation_brief
        ai_keywords = ["ai regulation", "artificial intelligence", "gpt", "llm", "openai", "eu ai act", "ai safety"]
        if any(kw in all_titles for kw in ai_keywords):
            matched = next((kw for kw in ai_keywords if kw in all_titles), "AI")
            missions.append(GeneratedMission(
                title="AI gündem özeti hazırla (5dk)",
                priority="P3",
                category="study",
                energy_cost="medium",
                duration_minutes=10,
                deadline_hours=8,
                tags=["news", "ai", "briefing", "awareness"],
                why=f"📰 '{matched.title()}' ile ilgili haberler var. Kısa özet hazırlamak stratejik farkındalık sağlar.",
                pack_name=self.name,
                rule_name="ai_regulation_brief",
                sources=["news"],
                confidence=0.7,
            ))
        
        # Rule: tech_layoffs_impact
        layoff_keywords = ["layoff", "layoffs", "job cuts", "workforce reduction", "downsizing"]
        if any(kw in all_titles for kw in layoff_keywords):
            missions.append(GeneratedMission(
                title="Sektör işten çıkarma haberleri: etki analizi",
                priority="P3",
                category="work",
                energy_cost="medium",
                duration_minutes=15,
                deadline_hours=24,
                tags=["news", "career", "analysis"],
                why="💼 Tech sektöründe işten çıkarma haberleri var. Kendi pozisyon ve network'ünü gözden geçir.",
                pack_name=self.name,
                rule_name="layoff_impact",
                sources=["news"],
                confidence=0.6,
            ))
        
        # Rule: security_alert
        security_keywords = ["data breach", "hack", "vulnerability", "cyber attack", "ransomware", "security flaw"]
        if any(kw in all_titles for kw in security_keywords):
            matched = next((kw for kw in security_keywords if kw in all_titles), "security")
            missions.append(GeneratedMission(
                title="Güvenlik kontrolü: sistemleri gözden geçir",
                priority="P2",
                category="dev",
                energy_cost="medium",
                duration_minutes=20,
                deadline_hours=4,
                tags=["news", "security", "audit", "critical"],
                why=f"🔒 '{matched.title()}' haberi var. Kendi sistemlerinde benzer zafiyet kontrolü yap.",
                pack_name=self.name,
                rule_name="security_review",
                sources=["news"],
                confidence=0.75,
            ))
        
        # Rule: general_brief
        if news and len(news) > 0:
            top_title = news[0].get("title", "gündem") if isinstance(news[0], dict) else str(news[0])
            missions.append(GeneratedMission(
                title="Gündemi tara: 5dk hızlı okuma",
                priority="P4",
                category="study",
                energy_cost="low",
                duration_minutes=5,
                deadline_hours=12,
                tags=["news", "awareness", "daily"],
                why=f"📱 Günün öne çıkan haberi: '{top_title[:50]}...'",
                pack_name=self.name,
                rule_name="general_brief",
                sources=["news"],
                confidence=0.5,
            ))
        
        return missions


# Registry of all rule packs
RULE_PACKS: list[RulePack] = [
    WeatherPack(),
    CalendarPack(),
    GitHubPack(),
    NewsPack(),
]


def evaluate_all_packs(context: dict[str, Any], preferences: dict[str, Any] = None) -> list[GeneratedMission]:
    """Evaluate all rule packs against context and return all generated missions."""
    all_missions = []
    
    for pack in RULE_PACKS:
        try:
            missions = pack.evaluate(context, preferences)
            all_missions.extend(missions)
        except Exception as e:
            # Log but don't fail
            print(f"Error in pack {pack.name}: {e}")
    
    return all_missions


def find_scheduling_conflicts(missions: list[GeneratedMission], calendar_events: list[dict]) -> None:
    """Update missions with scheduling conflicts based on calendar."""
    if not calendar_events:
        return
    
    for mission in missions:
        if mission.suggested_time:
            # Simple conflict detection (could be more sophisticated)
            for event in calendar_events:
                event_time = event.get("time", "")
                if event_time and mission.suggested_time and event_time in mission.suggested_time:
                    mission.conflicts.append(f"Çakışma: {event.get('title', 'Event')} @ {event_time}")
